In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import sbibm
import sbibm.visualisation

import altair as alt
from altair_saver import save
alt.renderers.enable('jupyterlab')

RendererRegistry.enable('jupyterlab')

In [3]:
num_obs_map = {1000: "10³", 10000: "10⁴", 100000: "10⁵"}
num_sims_remap = {"10³": "1e3", "10⁴": "1e4", "10⁵": "1e5"}
relevant_tasks = ["gaussian_linear_uniform", "slcp_distractors", "slcp", "two_moons", "gaussian_mixture"]

# Get the files from marginalized sbibm

In [4]:
sbibm_df = pd.read_csv("../marginalize_sbibm/marginal-c2st-summary.csv", index_col=0)
sbibm_df['num_simulations'] = sbibm_df['num_simulations'].map(num_obs_map)

In [5]:
sbibm_df.columns

Index(['task', 'num_simulations', 'num_observation', 'algorithm', 'seed', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', '[0, 1]', '[0, 2]',
       '[0, 3]', '[0, 4]', '[0, 5]', '[0, 6]', '[0, 7]', '[0, 8]', '[0, 9]',
       '[1, 2]', '[1, 3]', '[1, 4]', '[1, 5]', '[1, 6]', '[1, 7]', '[1, 8]',
       '[1, 9]', '[2, 3]', '[2, 4]', '[2, 5]', '[2, 6]', '[2, 7]', '[2, 8]',
       '[2, 9]', '[3, 4]', '[3, 5]', '[3, 6]', '[3, 7]', '[3, 8]', '[3, 9]',
       '[4, 5]', '[4, 6]', '[4, 7]', '[4, 8]', '[4, 9]', '[5, 6]', '[5, 7]',
       '[5, 8]', '[5, 9]', '[6, 7]', '[6, 8]', '[6, 9]', '[7, 8]', '[7, 9]',
       '[8, 9]', '1-dim mean', '1-dim var', '2-dim mean', '2-dim var', 'path',
       'folder'],
      dtype='object')

In [6]:
sbibm_result = sbibm_df.groupby([
    "task", 
    "num_simulations", 
#     "num_observation", 
    "algorithm",
]).agg(**{
#     "kl fixed 1-dim avg": ("KLD_FIX-1-dim mean", "mean"),
#     "kl fixed 2-dim avg": ("KLD_FIX-2-dim mean", "mean"),
    "c2st 1-dim avg": ("1-dim mean", "mean"),
    "c2st 2-dim avg": ("2-dim mean", "mean"),
})  # .loc['lotka_volterra', "10³"]
# print(sbibm_result)
sbibm_result.loc['two_moons']

                           c2st 1-dim avg  c2st 2-dim avg
num_simulations algorithm
10³             NLE              0.620182        0.764720
                NPE              0.594060        0.713450
                NRE              0.658005        0.823250
                REJ-ABC          0.750385        0.956150
                SMC-ABC          0.697060        0.908875
                SNLE             0.559593        0.653795
                SNPE             0.562393        0.646305
                SNRE             0.591803        0.658745
10⁴             NLE              0.581953        0.701185
                NPE              0.539565        0.604915
                NRE              0.616065        0.762875
                REJ-ABC          0.606378        0.842335
                SMC-ABC          0.556943        0.692380
                SNLE             0.534910        0.572315
                SNPE             0.512005        0.555270
                SNRE             0.565387        0.585875
10⁵             NLE              0.565480        0.660010
                NPE              0.516775        0.544905
                NRE              0.560210        0.625445
                REJ-ABC          0.543267        0.655590
                SMC-ABC          0.515943        0.652495
                SNLE             0.540342        0.582330
                SNPE             0.507010        0.533435
                SNRE             0.548600        0.564475

# From tmnre

In [7]:
file = "reports/swyft_uniform_2d_results_budget.csv"

def put_in_bins(x):
    if 0 <= x and x <= 1500:
        return 1_000
    elif 1501 <= x and x <= 15000:
        return 10_000
    else:
        return 100_000



swyft = pd.read_csv(file, index_col=0)

# special for our stochastic one
swyft["num_simulations"] = swyft["num_constraining_simulations"].map(put_in_bins)
swyft

,task,num_simulations,num_constraining_simulations,num_observation,algorithm,seed,dimension,rounds,"C2ST (0,)","C2ST (1,)",...,"KLD_FIX (7, 9)","KLD_FIX (4, 6)","KLD_FIX (6, 8)","KLD_FIX (5, 7)","KLD_FIX (3, 8)","KLD_FIX (0, 6)","KLD_FIX (1, 8)","KLD_FIX (6,)","KLD_FIX (1, 7)","KLD_FIX (0, 9)"
0,slcp,100000,100647,10,tmnre,3254095118,5,1,0.63675,0.65310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,slcp,100000,104968,3,tmnre,221300905,5,1,0.52980,0.54690,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,slcp,100000,99678,7,tmnre,622829621,5,1,0.53315,0.61730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,slcp,10000,10546,10,tmnre,1259500845,5,1,0.58595,0.62285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,slcp,100000,99616,8,tmnre,2302766548,5,1,0.51390,0.84670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,slcp_distractors,100000,100091,1,tmnre,236924093,5,1,0.52345,0.62905,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,slcp_distractors,1000,1035,4,tmnre,2895523053,5,1,0.63915,0.96210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,slcp_distractors,1000,957,7,tmnre,2184000798,5,1,0.65365,0.88070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,slcp_distractors,100000,100713,9,tmnre,3896778178,5,1,0.53420,0.73435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,slcp,10000,10001,3,tmnre,3064270973,5,1,0.57825,0.60195,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
swyft["RT"].sum()

220838.20588999998

In [9]:
# too many sims?
had_too_many_sims = swyft["num_constraining_simulations"] > swyft["num_simulations"]
print("Number of sims which were allowed too many to constrain", sum(had_too_many_sims))

printable_columns = ["task", "num_constraining_simulations", "num_observation"]
swyft[had_too_many_sims][printable_columns].sort_values(["task", "num_observation"])

Number of sims which were allowed too many to constrain 105

                        task  num_constraining_simulations  num_observation
71   gaussian_linear_uniform                        103129                1
88   gaussian_linear_uniform                         10035                1
60   gaussian_linear_uniform                          1027                2
67   gaussian_linear_uniform                        102039                2
81   gaussian_linear_uniform                         10272                2
..                       ...                           ...              ...
100                two_moons                          1027                9
102                two_moons                         10393                9
118                two_moons                        100439                9
89                 two_moons                        104919               10
106                two_moons                          1046               10

[105 rows x 3 columns]

In [10]:
# rename sims to match
swyft['num_simulations'] = swyft['num_simulations'].map(num_obs_map)

In [11]:
# which ones had at least one zoomin
swyft[swyft["rounds"] != 1]["task"].unique()

array(['slcp', 'gaussian_mixture', 'gaussian_linear_uniform', 'two_moons'],
      dtype=object)

In [12]:
# are there any difference between sbibm marginalized and this?
sbibm_relevant = sbibm_df[sbibm_df["task"].isin(relevant_tasks)]
merged = sbibm_relevant.merge(
    swyft, 
    on=["task", "num_simulations", "num_observation"],
    how="left",
    indicator=True,
)
columns = ["task", "num_simulations", "num_observation"]
merged[merged['_merge'] == 'left_only'][columns].drop_duplicates().sort_values(columns)

Empty DataFrame
Columns: [task, num_simulations, num_observation]
Index: []

In [13]:
metrics_to_combine = {
#     "kl fixed 1-dim avg": ("KLD_FIX-1-dim mean", "mean"),
#     "kl fixed 2-dim avg": ("KLD_FIX-2-dim mean", "mean"),
    "c2st 1-dim avg": ("C2ST 1-dim mean", "mean"),
}
if "C2ST 2-dim mean" in swyft.columns:
    metrics_to_combine.update({"c2st 2-dim avg": ("C2ST 2-dim mean", "mean")})

swyft_result = swyft.groupby([
    "task", 
    "num_simulations", 
#     "num_observation", 
    "algorithm",
]).agg(**metrics_to_combine)
swyft_result

                                                   c2st 1-dim avg  \
task                    num_simulations algorithm
gaussian_linear_uniform 10³             tmnre            0.587281
                        10⁴             tmnre            0.530641
                        10⁵             tmnre            0.509203
gaussian_mixture        10³             tmnre            0.678205
                        10⁴             tmnre            0.541510
                        10⁵             tmnre            0.517097
slcp                    10³             tmnre            0.730239
                        10⁴             tmnre            0.639700
                        10⁵             tmnre            0.589901
slcp_distractors        10³             tmnre            0.784208
                        10⁴             tmnre            0.720930
                        10⁵             tmnre            0.627692
two_moons               10³             tmnre            0.636345
                        10⁴             tmnre            0.547440
                        10⁵             tmnre            0.519855

                                                   c2st 2-dim avg
task                    num_simulations algorithm
gaussian_linear_uniform 10³             tmnre            0.635547
                        10⁴             tmnre            0.550524
                        10⁵             tmnre            0.525162
gaussian_mixture        10³             tmnre            0.775395
                        10⁴             tmnre            0.679445
                        10⁵             tmnre            0.549890
slcp                    10³             tmnre            0.861641
                        10⁴             tmnre            0.762426
                        10⁵             tmnre            0.715465
slcp_distractors        10³             tmnre            0.890414
                        10⁴             tmnre            0.839354
                        10⁵             tmnre            0.754893
two_moons               10³             tmnre            0.860875
                        10⁴             tmnre            0.655775
                        10⁵             tmnre            0.550450

# Combine

In [14]:
combined = pd.concat([swyft_result, sbibm_result]).sort_index()
combined.loc["slcp"].sort_values("c2st 1-dim avg")
# sbibm_result.join(swyft_result, on=["task", "num_simulations"], how='inner')

                           c2st 1-dim avg  c2st 2-dim avg
num_simulations algorithm
10⁵             SNLE             0.525365        0.543238
                SNPE             0.546987        0.582830
                NLE              0.554348        0.599687
                SNRE             0.560103        0.612055
10⁴             SNLE             0.564206        0.610173
10⁵             tmnre            0.589901        0.715465
                NPE              0.592778        0.668350
10⁴             NLE              0.598044        0.654428
                SNPE             0.607068        0.689357
                tmnre            0.639700        0.762426
                NPE              0.660974        0.759420
                SNRE             0.665306        0.765081
10³             SNLE             0.677779        0.770702
                NLE              0.697405        0.802885
10⁵             NRE              0.699014        0.793381
10⁴             NRE              0.704172        0.806459
10³             tmnre            0.730239        0.861641
10⁵             SMC-ABC          0.731324        0.842858
                REJ-ABC          0.732435        0.845044
10³             SNRE             0.736500        0.847678
10⁴             SMC-ABC          0.745831        0.859302
10³             SNPE             0.751628        0.856949
                NRE              0.754900        0.865406
10⁴             REJ-ABC          0.762543        0.874695
10³             NPE              0.771705        0.878986
                SMC-ABC          0.778530        0.890926
                REJ-ABC          0.782907        0.896468

# Now let's see what sbibm plotting can do

In [15]:
def split_metric_by_task_dimension(df, metric: str = "C2ST"):
    shared_columns = ["task", "num_simulations", "num_observation", "algorithm"]
    all_columns = shared_columns + [metric]
    out = []
    for (_, r) in df.iterrows():
        oneD = r[shared_columns]
        oneD["task"] = r["task"] + "_1d"
        oneD["C2ST"] = r[f"{metric} 1-dim mean"]
        
        twoD = r[shared_columns]
        twoD["task"] = r["task"] + "_2d"
        twoD["C2ST"] = r[f"{metric} 2-dim mean"]
        
        out.extend([oneD.to_frame().T, twoD.to_frame().T])
    return pd.concat(out)

In [16]:
# Do the preparing

target_1d_metric_name = "C2ST 1-dim mean"
target_2d_metric_name = "C2ST 2-dim mean"
sbibm_df = sbibm_df.rename(columns={'1-dim mean': target_1d_metric_name, "2-dim mean": target_2d_metric_name})
print(sbibm_df["algorithm"].unique().tolist())
print()

['SMC-ABC', 'NRE', 'REJ-ABC', 'NLE', 'SNPE', 'SNRE', 'SNLE', 'NPE']

In [17]:
sbibm_df['algorithm'] = sbibm_df['algorithm'].map(lambda x: " REJ-ABC" if x == 'REJ-ABC' else x)
swyft['algorithm'] = swyft['algorithm'].map(lambda x: " Our Method" if x == 'tmnre' else x)
color_dict = {
    'REJ-ABC': "#4A8CFB", 
    'NLE': "#60D098", 
    'NPE': "#CC66CC",
    'NRE': "#FFCA58", 
    'NRE_B': "#FFCA58", 
    'SMC-ABC': "#215FC6",
    'SNLE': "#339966", 
    'SNPE': "#990099", 
    'SNRE': "#FFA60A", 
    'SNRE_B': "#FFA60A", 
    "CMNRE": "#000000",
}
task_map = lambda name: sbibm.get_task(name).name_display

In [18]:
analyze = pd.concat([sbibm_df, swyft])
for task in swyft['task'].unique():
    analyze_subset = analyze.query(f"task == '{task}'")
    analyze_subset = split_metric_by_task_dimension(analyze_subset)
    
    analyze_subset["C2ST-ddm"] = analyze_subset["C2ST"]
    analyze_subset["algorithm"] = analyze_subset["algorithm"].map(lambda x: "NRE_B" if x == "NRE" else x)
    analyze_subset["algorithm"] = analyze_subset["algorithm"].map(lambda x: "SNRE_B" if x == "SNRE" else x)
    analyze_subset["algorithm"] = analyze_subset["algorithm"].map(lambda x: "  TMNRE" if x == " Our Method" else x)
    analyze_subset["num_simulations"] = analyze_subset["num_simulations"].map(num_sims_remap)
    
    do_column_label = True if task == "two_moons" else False
    do_x_label = True if task == "gaussian_mixture" else False
    column_title = "Number of Simulations" if task == "gaussian_mixture" else ""
    
    fig = sbibm.visualisation.fig_metric(
        analyze_subset, 
        title=f"● 1-dim / ■ 2-dim Marginal {task_map(task)}",
        metric="C2ST-ddm",
        config="custom",
        keywords={
            "shape": alt.Shape('task:N', legend=None), 
            "detail": alt.Detail('task:N'),
        },
        colors_dict=color_dict,
        labels=do_column_label,
        x_axis_kwargs={"labels": do_x_label},
        column_title=column_title,
    )
    save(fig, f"figures/{task}.png")